import { AIModel, Conversation } from './types'

export const PROVIDER_COLORS = {
  nvidia: '#76B900',
  openrouter: '#10A37F',
} as const

// ─── AI Models with technical metadata ───────────────────────────────────────────

export const aiModels: AIModel[] = [
  // ==========================================
  // NVIDIA PLATFORM MODELS (provider: 'nvidia')
  // ==========================================
  {
    id: "nv-deepseek-v4-flash",
    name: "DeepSeek V4 Flash",
    company: "DeepSeek",
    size: "284B",
    provider: "nvidia",
    endpoint: "deepseek/v4-flash",
    alias: "deepseek-ai/deepseek-v4-flash",
    status: "FREE",
    badge: "Reasoning",
    description: "An ultra-fast, reasoning-optimized Mixture-of-Experts (MoE) model. Excellent for fast coding iteration and low-latency agentic planning.",
    strengths: ["Fast Reasoning", "High Throughput", "Agentic Tasks", "Code Generation"],
    contextWindow: 1000000,
    parameters: "284B MoE (13B active)",
    reasoningScore: 88,
    codingScore: 92,
    providerColor: PROVIDER_COLORS.nvidia,
    isNew: true
  },
  {
    id: "nv-deepseek-v4-pro",
    name: "DeepSeek V4 Pro",
    company: "DeepSeek",
    size: "1.6T MoE",
    provider: "nvidia",
    endpoint: "deepseek/v4-pro",
    alias: "deepseek-ai/deepseek-v4-pro",
    status: "FREE",
    badge: "Frontier",
    description: "DeepSeek's flagship Mixture-of-Experts model, featuring 1.6T total parameters. Built for deep multi-step reasoning, complex coding, and large-context mathematical problem solving.",
    strengths: ["Frontier Reasoning", "Complex Coding", "Mathematics", "Agentic Planning"],
    contextWindow: 1000000,
    parameters: "1.6T MoE (49B active)",
    reasoningScore: 98,
    codingScore: 97,
    providerColor: PROVIDER_COLORS.nvidia,
    isNew: true
  },
  {
    id: "nv-mistral-small-4",
    name: "Mistral Small 4",
    company: "Mistral",
    size: "119B",
    provider: "nvidia",
    endpoint: "mistral/small-4",
    alias: "mistralai/mistral-small-4-119b-2603",
    status: "FREE",
    badge: "Balanced",
    description: "Mistral Small 4 integrates native reasoning, multimodal image understanding, and code intelligence into a highly optimized, low-latency 119B MoE model.",
    strengths: ["Balanced Reasoning", "Vision & Multimodal", "Low Latency", "Function Calling"],
    contextWindow: 262144,
    parameters: "119B MoE (6.5B active)",
    reasoningScore: 84,
    codingScore: 82,
    providerColor: PROVIDER_COLORS.nvidia,
    isNew: true
  },
  {
    id: "nv-ministral-14b-instruct",
    name: "Ministral 14B Instruct",
    company: "Mistral",
    size: "14B",
    provider: "nvidia",
    endpoint: "mistral/ministral-14b",
    alias: "mistralai/ministral-14b-instruct-2512",
    status: "FREE",
    badge: "Fast",
    description: "A third-generation state-of-the-art edge model from Mistral AI, delivering powerful reasoning, local speed, and native image understanding.",
    strengths: ["On-device Speed", "Vision Support", "Strong Edge Reasoning", "Low Resource Usage"],
    contextWindow: 262144,
    parameters: "14B Dense",
    reasoningScore: 78,
    codingScore: 74,
    providerColor: PROVIDER_COLORS.nvidia,
    isNew: false
  },
  {
    id: "nv-mixtral-8x7b-instruct",
    name: "Mixtral 8x7B Instruct",
    company: "Mistral",
    size: "47B MoE",
    provider: "nvidia",
    endpoint: "mistral/mixtral-8x7b",
    alias: "mistralai/mixtral-8x7b-instruct-v0.1",
    status: "FREE",
    badge: "General",
    description: "Mistral's classic high-performance sparse Mixture-of-Experts model. An industry benchmark for general text processing and prompt execution.",
    strengths: ["General Text", "Multilingual Dialogue", "Apache-2.0 License", "Stable Baselines"],
    contextWindow: 32768,
    parameters: "46.7B MoE (12.9B active)",
    reasoningScore: 70,
    codingScore: 68,
    providerColor: PROVIDER_COLORS.nvidia,
    isNew: false
  },
  {
    id: "nv-nemotron-3-super",
    name: "Nemotron-3 Super",
    company: "NVIDIA",
    size: "120B",
    provider: "nvidia",
    endpoint: "nvidia/nemotron-3-super",
    alias: "nvidia/nemotron-3-super-120b-a12b",
    status: "FREE",
    badge: "Reasoning",
    description: "NVIDIA's hybrid Mamba-Transformer MoE model, engineered specifically for multi-agent software engineering, cybersecurity, and coding scaffolds.",
    strengths: ["Multi-Agent Planning", "Cybersecurity", "Multi-Token Prediction", "Mamba-Transformer Hybrid"],
    contextWindow: 1048576,
    parameters: "120B MoE (12B active)",
    reasoningScore: 92,
    codingScore: 90,
    providerColor: PROVIDER_COLORS.nvidia,
    isNew: true
  },
  {
    id: "nv-nemotron-3-ultra",
    name: "Nemotron-3 Ultra",
    company: "NVIDIA",
    size: "550B",
    provider: "nvidia",
    endpoint: "nvidia/nemotron-3-ultra",
    alias: "nvidia/nemotron-3-ultra-550b-a55b",
    status: "FREE",
    badge: "Agentic",
    description: "NVIDIA's premier LatentMoE model, interleaving Mamba-2 and Transformer layers. Native support for inference-time reasoning budgets and deep multi-hop workflows.",
    strengths: ["Frontier Reasoning", "Deep Thinking", "Mamba-2 LatentMoE", "Long-horizon Agentic Workflows"],
    contextWindow: 1048576,
    parameters: "550B MoE (55B active)",
    reasoningScore: 97,
    codingScore: 95,
    providerColor: PROVIDER_COLORS.nvidia,
    isNew: true
  },
  {
    id: "nv-gemma-4",
    name: "Gemma 4",
    company: "Google",
    size: "31B IT",
    provider: "nvidia",
    endpoint: "google/gemma-4",
    alias: "google/gemma-4-31b-it",
    status: "FREE",
    badge: "Thinking",
    description: "Google's fourth-generation workstation model. Features natively integrated multimodal reasoning, system prompts, and Gemini-based open weights intelligence.",
    strengths: ["Advanced Reasoning", "System Prompts", "Workstation Performance", "Image Inputs"],
    contextWindow: 131072,
    parameters: "31B Dense",
    reasoningScore: 89,
    codingScore: 87,
    providerColor: PROVIDER_COLORS.nvidia,
    isNew: true
  },
  {
    id: "nv-qwen-3-5",
    name: "Qwen 3.5",
    company: "Alibaba",
    size: "122B",
    provider: "nvidia",
    endpoint: "alibaba/qwen-3-5",
    alias: "qwen/qwen3.5-122b-a10b",
    status: "FREE",
    badge: "Coding",
    description: "Alibaba's advanced open-weight model with 122B parameters. Offers state-of-the-art coding abilities, multilingual capabilities, and system engineering tasks.",
    strengths: ["Advanced Coding", "Multilingual Chat", "Mathematics", "Tool Calls"],
    contextWindow: 131072,
    parameters: "122B Dense",
    reasoningScore: 91,
    codingScore: 94,
    providerColor: PROVIDER_COLORS.nvidia,
    isNew: true
  },
  {
    id: "nv-minimax-m2-7",
    name: "MiniMax M2.7",
    company: "MiniMax",
    size: "M2.7",
    provider: "nvidia",
    endpoint: "minimax/m2-7",
    alias: "minimaxai/minimax-m2.7",
    status: "FREE",
    badge: "General",
    description: "MiniMax M2.7 is built using an iterative self-evolving framework, making it highly competent for agentic workflows, self-debugging, and structured JSON output.",
    strengths: ["Self-Evolution", "Self-Debugging", "Structured Output", "Agent Orchestration"],
    contextWindow: 209715,
    parameters: "230B MoE (10B active)",
    reasoningScore: 87,
    codingScore: 91,
    providerColor: PROVIDER_COLORS.nvidia,
    isNew: true
  },
  {
    id: "nv-phi-4-mini-instruct",
    name: "Phi-4 Mini Instruct",
    company: "Microsoft",
    size: "3.8B",
    provider: "nvidia",
    endpoint: "microsoft/phi-4-mini",
    alias: "microsoft/phi-4-mini-instruct",
    status: "FREE",
    badge: "Edge",
    description: "Microsoft's lightweight Small Language Model (SLM) trained on curated synthetic datasets. Delivers highly competitive math, coding, and logical reasoning at minimal cost.",
    strengths: ["Math & Logic", "Extreme Speed", "Edge Deployments", "Function Calling"],
    contextWindow: 131072,
    parameters: "3.8B Dense",
    reasoningScore: 82,
    codingScore: 80,
    providerColor: PROVIDER_COLORS.nvidia,
    isNew: false
  },
  {
    id: "nv-llama-3-3",
    name: "Llama 3.3",
    company: "Meta",
    size: "70B Instruct",
    provider: "nvidia",
    endpoint: "meta/llama-3-3",
    alias: "meta/llama-3.3-70b-instruct",
    status: "FREE",
    badge: "Balanced",
    description: "Meta's flagship 70B parameter open-weights model, fine-tuned for complex instruction following, multilingual dialogue, and general-purpose reasoning.",
    strengths: ["Instruction Following", "Multilingual Chat", "General Reasoning", "Balanced Latency"],
    contextWindow: 131072,
    parameters: "70B Dense",
    reasoningScore: 86,
    codingScore: 84,
    providerColor: PROVIDER_COLORS.nvidia,
    isNew: false
  },
  {
    id: "nv-step-3-7-flash",
    name: "Step-3.7 Flash",
    company: "StepFun",
    size: "Flash",
    provider: "nvidia",
    endpoint: "stepfun/step-3-7-flash",
    alias: "stepfun-ai/step-3.7-flash",
    status: "FREE",
    badge: "Fast",
    description: "A high-throughput, sparse vision-language Mixture-of-Experts (MoE) model. Capable of generating up to 400 tokens per second for real-time agentic interactions.",
    strengths: ["Vision-Language", "High Speed", "Fast Coding", "Real-time Agents"],
    contextWindow: 262144,
    parameters: "198B MoE",
    reasoningScore: 83,
    codingScore: 85,
    providerColor: PROVIDER_COLORS.nvidia,
    isNew: true
  },
  {
    id: "nv-kimi-k2-6",
    name: "Kimi K2.6",
    company: "Moonshot",
    size: "K2.6",
    provider: "nvidia",
    endpoint: "moonshot/kimi-k2-6",
    alias: "moonshotai/kimi-k2.6",
    status: "FREE",
    badge: "Chat",
    description: "Moonshot AI's native agentic and coding specialist, highly optimized for large-scale code synthesis, site generation, and long-horizon tasks.",
    strengths: ["Vibe Coding", "Entire Site Gen", "Multi-Agent Orchestration", "Long Coding Horizon"],
    contextWindow: 209715,
    parameters: "K2.6 MoE",
    reasoningScore: 89,
    codingScore: 92,
    providerColor: PROVIDER_COLORS.nvidia,
    isNew: true
  },
  {
    id: "nv-gpt-oss-20b",
    name: "GPT-OSS 20B",
    company: "OpenAI",
    size: "20B",
    provider: "nvidia",
    endpoint: "openai/gpt-oss-20b",
    alias: "openai/gpt-oss-20b",
    status: "FREE",
    badge: "Local",
    description: "OpenAI's efficient 20B open-weights model, designed for on-device and local workstation tasks with MXFP4 optimization.",
    strengths: ["Local Speed", "Quantized Efficiency", "General Purpose", "Apache-2.0"],
    contextWindow: 131072,
    parameters: "20B Dense",
    reasoningScore: 79,
    codingScore: 76,
    providerColor: PROVIDER_COLORS.nvidia,
    isNew: true
  },
  {
    id: "nv-gpt-oss-120b",
    name: "GPT-OSS 120B",
    company: "OpenAI",
    size: "120B",
    provider: "nvidia",
    endpoint: "openai/gpt-oss-120b",
    alias: "openai/gpt-oss-120b",
    status: "FREE",
    badge: "Reasoning",
    description: "OpenAI's high-intelligence open-weights model, delivering advanced multi-step reasoning and logical analysis under an open license.",
    strengths: ["Multi-step Logic", "Apache-2.0 License", "Reasoning Benchmarks", "Structured Chat"],
    contextWindow: 131072,
    parameters: "120B Dense",
    reasoningScore: 93,
    codingScore: 90,
    providerColor: PROVIDER_COLORS.nvidia,
    isNew: true
  },
  {
    id: "nv-seed-oss-36b-instruct",
    name: "Seed-OSS 36B Instruct",
    company: "ByteDance",
    size: "36B",
    provider: "nvidia",
    endpoint: "bytedance/seed-oss-36b",
    alias: "bytedance/seed-oss-36b-instruct",
    status: "FREE",
    badge: "General",
    description: "ByteDance's open-weights model featuring a natively long context window and an adjustable inference-time thinking budget for deep logic.",
    strengths: ["Long Context (512K)", "Thinking Budget", "Document Processing", "Logical Depth"],
    contextWindow: 524288,
    parameters: "36B Dense",
    reasoningScore: 84,
    codingScore: 83,
    providerColor: PROVIDER_COLORS.nvidia,
    isNew: true
  },

  // ==============================================
  // OPENROUTER API MODELS (provider: 'openrouter')
  // ==============================================
  {
    id: "or-nvidia-nemotron-3-ultra",
    name: "Nemotron 3 Ultra (free)",
    company: "NVIDIA",
    size: "550B MoE",
    endpoint: "nvidia/nemotron-3-ultra-550b-a55b:free",
    provider: "openrouter",
    status: "FREE",
    badge: "Reasoning",
    description: "OpenRouter's free tier access to NVIDIA's most powerful LatentMoE model, specializing in frontier reasoning and long context.",
    strengths: ["Frontier Reasoning", "LatentMoE", "1M Context Window", "Free Tier Access"],
    contextWindow: 1048576,
    parameters: "550B MoE (55B active)",
    reasoningScore: 97,
    codingScore: 95,
    providerColor: PROVIDER_COLORS.openrouter,
    isNew: true
  },
  {
    id: "or-nex-agi-nex-n2-pro",
    name: "Nex-N2-Pro (free)",
    company: "Nex AGI",
    size: "397B MoE",
    endpoint: "nex-agi/nex-n2-pro:free",
    provider: "openrouter",
    status: "FREE",
    badge: "Programming",
    description: "Engineered specifically for agentic workflows and environment execution. Built on Qwen 3.5 base for elite software engineering capabilities.",
    strengths: ["Software Engineering", "Agentic Thinking", "Environment Execution", "Tool Use"],
    contextWindow: 131072,
    parameters: "397B MoE (Qwen 3.5 base)",
    reasoningScore: 92,
    codingScore: 96,
    providerColor: PROVIDER_COLORS.openrouter,
    isNew: true
  },
  {
    id: "or-google-gemma-4-31b",
    name: "Gemma 4 31B (free)",
    company: "Google",
    size: "30.7B",
    endpoint: "google/gemma-4-31b-it:free",
    provider: "openrouter",
    status: "FREE",
    badge: "Roleplay",
    description: "Google's Gemma 4 31B model available for free on OpenRouter. Ideal for creative writing, logical roleplay, and system-level task planning.",
    strengths: ["Roleplay & Persona", "Logical Planning", "Multimodal Input", "Creative Tasks"],
    contextWindow: 131072,
    parameters: "30.7B Dense",
    reasoningScore: 89,
    codingScore: 87,
    providerColor: PROVIDER_COLORS.openrouter,
    isNew: true
  },
  {
    id: "or-google-gemma-4-26b-a4b",
    name: "Gemma 4 26B A4B (free)",
    company: "Google",
    size: "26B",
    endpoint: "google/gemma-4-26b-a4b-it:free",
    provider: "openrouter",
    status: "FREE",
    badge: "Thinking",
    description: "Google's sparse Mixture-of-Experts Gemma 4 variant. Highly resource-efficient while preserving deep thinking and instruction fidelity.",
    strengths: ["Deep Thinking MoE", "Fidelity Instruction", "High Speed", "Resource Optimized"],
    contextWindow: 131072,
    parameters: "26B MoE (4B active)",
    reasoningScore: 88,
    codingScore: 85,
    providerColor: PROVIDER_COLORS.openrouter,
    isNew: true
  },
  {
    id: "or-poolside-laguna-m-1",
    name: "Poolside: Laguna M.1 (free)",
    company: "Poolside",
    size: "M",
    endpoint: "poolside/laguna-m.1:free",
    provider: "openrouter",
    status: "FREE",
    badge: "Programming",
    description: "Poolside's specialized code-generation model, trained explicitly for long-horizon programming, architectural design, and test suites.",
    strengths: ["Long-horizon Coding", "Architectural Design", "Test Generation", "Code Autocomplete"],
    contextWindow: 65536,
    parameters: "M-Size Dense",
    reasoningScore: 81,
    codingScore: 94,
    providerColor: PROVIDER_COLORS.openrouter,
    isNew: true
  },
  {
    id: "or-nvidia-nemotron-3-nano-omni",
    name: "Nemotron 3 Nano Omni (free)",
    company: "NVIDIA",
    size: "30B A3B MoE",
    endpoint: "nvidia/nemotron-3-nano-omni:free",
    provider: "openrouter",
    status: "FREE",
    badge: "Multimodal",
    description: "A multi-modal perception model designed as a perception and audio/video context sub-agent, bypassing standard textual pipeline limits.",
    strengths: ["Perception Sub-Agent", "Natively Multimodal", "Video & Audio Inputs", "Low Context Latency"],
    contextWindow: 131072,
    parameters: "30B MoE (3B active)",
    reasoningScore: 80,
    codingScore: 78,
    providerColor: PROVIDER_COLORS.openrouter,
    isNew: true
  }
]

export const mockConversations: Conversation[] = []
